Style/CommentedKeyword:
  Exclude:
    - '**/*.rb'
    - 'bin/*'
Style/Documentation:
  Exclude:
    - '**/*.rb'
    - 'bin/*'
Naming/ClassAndModuleCamelCase:
  Exclude:
    - '**/*.rb'
    - 'bin/*'
Style/MethodLength:
  Exclude:
    - '**/*.rb'
    - 'bin/*'
