Style/CommentedKeyword:
  Exclude:
    - '**/*.rb'
    - '**/main'
Style/Documentation:
  Exclude:
    - '**/*.rb'
    - '**/main'
Naming/ClassAndModuleCamelCase:
  Exclude:
    - '**/*.rb'
    - '**/main'
Style/MethodLength:
  Exclude:
    - '**/*.rb'
    - '**/main'
