Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodLength:
  Enabled: false
