#!/usr/bin/env zsh
#
#
set -u -e -o pipefail -x

cd $(dirname "$0")/..

rm -f -r dist
mkdir dist
cp -r src dist/src
cp -r spec dist/spec

cd dist
tsc
da fs rename files with ext .js .mjs
da fs remove files with ext .ts
cd ..
tree dist
