#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

set -x
if test "$@" = "" ; then
  local TARGET="js crystal"
  local FILE_TARGET="*"
else
  local TARGET="$1";
  local FILE_TARGET="${2:-"*"}"
fi

cd "$(dirname "$0")"/..
sh/build

case "$@" in
  *js*)
    # NOTE: sort in reverse to run DA_Spec specs first.
    for file in $(find dist/spec/ -type f -iname "${FILE_TARGET}.spec.mjs" | sort -r -h) ; do
      echo "=== $file"
      node $file
    done
    ;;
  *)
    echo "$@"
    exit 1
esac

