#!/usr/bin/env zsh
#
#

set -u -e -o pipefail

cd "$(dirname "$0")"/..
shards build -- --warnings all --release
# rm -r -f dist
# tsc
# cd dist
# da fs rename files with ext .js .mjs
# da fs fix mjs import from extensions
# cd ..
# tree dist



