#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
PATH="$PATH:$THIS_DIR/../process/bin"
PATH="$PATH:$THIS_DIR/../sh_color/bin"

if [[ -z "$@" ]]; then
  local +x ACTION=watch
else
  local +x ACTION="$1"; shift
fi

export IS_DEV_BUILD=yes
case "$ACTION" in

  watch)
    da_html.cr specs run || :
    process watch "-r tmp/out -r examples -r sh -r src -r specs" "da_html.cr specs run"
    ;;

  run)
    cd "$THIS_DIR"
    mkdir -p tmp/out
    case "${CHANGED_FILE:-}" in
      *.cr)
        sh_color ORANGE "=== {{Compiling}} specs..."
        my_crystal crystal build -o tmp/specs.cr specs/specs.cr
        ;;
      */tmp/out/args) : ;;
      */tmp/out*) return 0 ;;
    esac

    reset
    sh_color ORANGE "=== {{Running}} specs..."
    if [[ -s "tmp/out/args" ]]; then
      tmp/specs.cr -e "$(cat tmp/out/args)" $@
    else
      tmp/specs.cr $@
    fi
    sh_color GREEN "=== {{DONE}} ==="
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

