#!/usr/bin/env bash
#
#
set -u -e -o pipefail


case "$*" in
  'help intro line')
    echo "Format strings: bold|red|... content string ..."
    exit 0
    ;;
esac

case "$1" in
  # doc: CMD bold|italics [string]
  bold)
    shift
    bold=$(tput bold)
    normal=$(tput sgr0)
    echo -e "$bold$*$normal"
    ;;

  italics)
    shift
    echo -e "\e[3m$*\e[0m"
    ;;
  # ==============================================

  # doc: CMD red|green|yellow|blue|white [string]
  red)
    shift
    echo -e "\e[31m$*\e[0m"
    ;;

  green)
    shift
    echo -e "\e[32m$*\e[0m"
    ;;

  yellow)
    shift
    echo -e "\e[33m$*\e[0m"
    ;;

  blue)
    shift
    echo -e "\e[34m$*\e[0m"
    ;;

  white) # doc: [content ...]
    shift
    echo -e "\e[37m$*\e[0m"
    ;;
  # ==============================================

  # doc: CMD doc [...file paths]
  doc)
    shift
    "$DA_SRC"/string/doc_format.rb "$@"
    ;;

  *)
    echo "!!! Unknown command: $*" >&2
    exit 1
    ;;
esac
