#!/usr/bin/env ruby
# frozen_string_literal: true

require "#{ENV['DA_SRC']}/ruby_lib/shell"

cmd = ARGV.join(' ')
main_cmd = ARGV.first
prog = __FILE__.split('/').last

case cmd
when '-h', '--help', 'help'
  puts "da #{prog} -h|--help|help  --  Show this message."
  puts "da #{prog} path/to/file    --  Extract documentation from file."
  exit 0

when 'help intro line'
  puts 'Extract documentation from a file.'
  exit 0
end

ftype = `file --mime "#{main_cmd}"`
case ftype
when /shellscript/
  contents = File.read(ARGV.last)
  previous = nil
  sub_cmd = Shell::String.bold(File.basename(ARGV.last.sub('/main', '')))
  puts "da #{sub_cmd} -h|--help|help - Show this message."
  contents.each_line do |line|
    new_line = (previous) ? "\nda #{sub_cmd} " : "da #{sub_cmd} "
    results = line.split(/(\))?\ +#\ +doc(\ +.+)?$/)
    next if results.size == 1
    raw_txt, paren, raw_doc, __newline = results
    doc = raw_doc.strip
    txt = raw_txt.strip.gsub(/['"]/, '')
    case doc
    when 'or'
      print "|#{txt}"
    when /or(\ +.+)/
      print "|#{txt} #{$1.strip}"
    when ''
      print "#{new_line}#{txt}"
      STDOUT.flush
    else
      print "#{new_line}#{[txt,doc].join(' ').strip}"
      STDOUT.flush
    end

    previous = txt
  end
  print "\n"
  STDOUT.flush
else
  system(*ARGV, '--help')
end # case
