#!/usr/bin/env bash
#
#
set -u -e -o pipefail


case "$*" in
  "-h"|"--help"|"help")
    echo "$0 -h|--help|help -- Show this message."
    echo "$0 bold|italics|faint -- Show this message."
    echo "$0 red|blue|green -- Show this message."
    echo
    exit 0
    ;;
  "help intro line")
    echo "Format strings: bold|red|... content string ..."
    exit 0
    ;;
esac

case "$*" in
  'bold '*)
    shift
    bold=$(tput bold)
    normal=$(tput sgr0)
    echo -e "$bold$*$normal"
    ;;
  "italics "*)
    shift
    echo -e "\e[3m$*\e[0m"
    ;;
  "red "*)
    shift
    echo -e "\e[31m$*\e[0m"
    ;;
  "green "*)
    shift
    echo -e "\e[32m$*\e[0m"
    ;;
  "yellow "*)
    shift
    echo -e "\e[33m$*\e[0m"
    ;;
  "blue "*)
    shift
    echo -e "\e[34m$*\e[0m"
    ;;
  "white "*)
    shift
    echo -e "\e[37m$*\e[0m"
    ;;
  *)
    echo "!!! Unknown command: $*" >&2
    exit 1
    ;;
esac
