#!/usr/bin/env bash
#
#
set -u -e -o pipefail
cd "$( dirname "$(realpath "$0")" )/.."
THIS_DIR="$PWD"


case "$@" in
  -h|help|--help)
    echo "--------------------------------------"
    echo "-- Use mise instead of this script."
    echo "--------------------------------------"
    echo "$DA_CMD latest|install"
    ;;

  "latest")
    url="https://github.com/crystal-lang/crystal/releases"
    href="$(curl --silent -L $url | grep -Po '/.+releases/download/.+linux-x86_64.+.gz' | head -n 1)"
    test -n "$href" || { echo "!!! Latest release not found." >&2; exit 1; }
    echo "https://github.com$href"
    ;;

  "install")
    case "$(lsb_release -a)" in
      *Ubuntu*)
        sudo apt install libssl-dev libxml2-dev libyaml-dev libgmp-dev
        ;;
      *)
        echo "Unknown system: $(lsb_release -a)" >&2
        exit 1
        ;;
    esac

    mkdir -p /progs/crystal
    cd /progs/crystal

    latest="$("$THIS_DIR/sh/crystal" latest)"
    dirname="$(basename "$latest" -linux-x86_64.tar.gz)"

    if ! test -d "$dirname" ; then
      # rm -f "$basename"
      wget --continue "$latest"
      tar xvzf "$(basename "$latest")"
      rm -f "current"
      ln -s "$dirname" "current"
      rm "$(basename "$latest")"
    fi

    current/bin/crystal --version
    ;;

  *)
    echo "!!! Unknown arguments: $*"
    exit 1
    ;;
esac

